version: "3"
services:
  db:
    image: mariadb:latest
    # image: mariadb:10.5.8
    # platform: linux/amd64
    volumes:
      - ./conf/mysql/conf.d:/etc/mysql/conf.d
      - ./conf/mysql/mariadb.conf.d:/etc/mysql/mariadb.conf.d
      - ./conf/mysql/mariadb.cnf:/etc/mysql/mariadb.cnf
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root_password_1234
      MYSQL_DATABASE: database_name
      MYSQL_USER: database_user
      MYSQL_PASSWORD: db_password_1234
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    # platform: linux/amd64
    restart: always
    ports: ["8888:80"]
    depends_on: ["db"]
    environment:
      TZ: Asia/Tokyo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  php:
    #image: php:7.4-fpm
    build:
      context: ./docker/php-fpm
    volumes:
      - ./conf/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./www/apps:/var/www/apps
      - ./www/error_pages:/usr/share/nginx/html
      - ./logs/php:/var/log
    restart: always
    environment:
      TZ: Asia/Tokyo
      APP_SCRIPT_PATH: /var/www/apps/
      APP_SCRIPT_NAME: 
    links:
      - db:db 
    depends_on: ["db"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/cert:/etc/nginx/cert
      - ./www/apps:/var/www/apps
      - ./www/error_pages:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    restart: always
    environment:
      TZ: Asia/Tokyo
    ports: ["80:80", "443:443"]
    depends_on: ["php"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  flask:
    build:
      context: ./docker/flask
    volumes:
      - ./www/flaskapps:/media/src
      #  - ./www/apps/storage:/media/storage
    restart: always
    tty: true
    environment:
      FLASK_DEBUG: 1
      TZ: Asia/Tokyo
    ports:
      - "5000:5000"
    command: flask run --host 0.0.0.0 --port 5000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
